### ISSUE TITLE
Is the code still under development?

### ISSUE THREAD

**Issue by kashismoney** [mybyte/tools#1]

**Comment by mybyte** [comment]
Nope. The main reason I developed this stuff was a bug with the merge cypher statement. It was fixed at some point so there's no need for the RMI stuff any more.

**Comment by kashismoney** [comment]
I was working with the clone repository of turtle loader. Is it also closed? I really need some help to import turtle(ontology) into neo4j?

**Comment by mybyte** [comment]
I might actually do some work on this. Not sure whether I'll stick with 
Sesame or use Jena though. Also, I think there's need for a more 
sophisticated data model design to add proper support for Ontologies.

**Comment by kashismoney** [comment]
Hi,
Yes I realized that. Do you know a way how I can import my turtle file into
neo4j? That will be a great help.
Thanks,
-km-

**Comment by mybyte** [comment]
It's fairly straight forward. Use either Sesame or Jena to load the 
files (http://jena.apache.org/documentation/io/), iterate over all 
classes / instances and push them into Neo4j using the Java API. Don't 
forget about relationships (object properties) though ;)

**Comment by kashismoney** [comment]
Hi,
I was wondering if you still have the turtle file you used in the turtleloader code?
Thanks,
-km-

**Comment by kashismoney** [comment]
I used your code with my turtle file. The code does not work?

**Comment by mybyte** [comment]
Hi!

I don't think so. If I remember correctly, I used dbpedia data. You can 
download it here: http://wiki.dbpedia.org/Downloads39

Regards,
Michael

**Comment by kashismoney** [comment]
Is there a way we could talk a lil bit?
My email is: kxmehdi@gmail.com
